"""empty message

Revision ID: 40b8c66d0a47
Revises: ae94777709f4
Create Date: 2023-08-13 23:55:13.460891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b8c66d0a47'
down_revision = 'ae94777709f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('planets_rotarion_period_key', type_='unique')
        batch_op.create_unique_constraint(None, ['rotation_period'])
        batch_op.drop_column('rotarion_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotarion_period', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planets_rotarion_period_key', ['rotarion_period'])
        batch_op.drop_column('rotation_period')

    # ### end Alembic commands ###
